# -*- coding: utf-8 -*-
"""크롤링.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kh-znxxnHWaVMVd2SzhRjxgW4oGyLj4L
"""

import pandas as pd

import bs4

import requests




url = "https://www.smu.ac.kr/kor/life/notice.do?mode=list&srCampus=smu&articleLimit=10&article.offset=0"

html = requests.get(url).text



soup = bs4.BeautifulSoup(html, "html.parser")



data = []

css_selector = ".board-thumb-content-wrap"



for tag in soup.select(css_selector):

  title = tag.select_one("td:nth-child(3) a").get_text(strip=True)

  link = "https://www.smu.ac.kr"+tag.select_one("td:nth-child(3) a")["href"]

  date = tag.select_one("li.board-thumb-content-date").get_text(strip=True)

  category = tag.select_one("span.cate").get_text(strip=True)

  data.append((title, date, category, link))





complement_data = pd.DataFrame(data=data, columns=["title", "date", "category", "link"])



complement_data.to_csv("smu_notice.csv", index=False, encoding="utf-8-sig")
fg.rss_file('docs/rss.xml')
